wmake libso .
Making dependency list for source file wideBandVariableExtinction.C
g++ -std=c++11 -m64 -Dlinux64 -DWM_ARCH_OPTION=64 -DWM_DP -DWM_LABEL_SIZE=32 -Wall -Wextra -Wold-style-cast -Wnon-virtual-dtor -Wno-unused-parameter -Wno-invalid-offsetof -O3  -DNoRepository -ftemplate-depth-100 -I/opt/openfoam5/src/finiteVolume/lnInclude -I/opt/openfoam5/src/meshTools/lnInclude -I/opt/openfoam5/src/thermophysicalModels/basic/lnInclude -I/opt/openfoam5/src/turbulenceModels/compressible/turbulenceModel/lnInclude -I/opt/openfoam5/src/regionModels/regionModel/lnInclude -IlnInclude -I. -I/opt/openfoam5/src/OpenFOAM/lnInclude -I/opt/openfoam5/src/OSspecific/POSIX/lnInclude   -fPIC -c subModels/extinctionModel/wideBandVariableExtinction/wideBandVariableExtinction.C -o Make/linux64GccDPInt32Opt/subModels/extinctionModel/wideBandVariableExtinction/wideBandVariableExtinction.o
g++ -std=c++11 -m64 -Dlinux64 -DWM_ARCH_OPTION=64 -DWM_DP -DWM_LABEL_SIZE=32 -Wall -Wextra -Wold-style-cast -Wnon-virtual-dtor -Wno-unused-parameter -Wno-invalid-offsetof -O3  -DNoRepository -ftemplate-depth-100 -I/opt/openfoam5/src/finiteVolume/lnInclude -I/opt/openfoam5/src/meshTools/lnInclude -I/opt/openfoam5/src/thermophysicalModels/basic/lnInclude -I/opt/openfoam5/src/turbulenceModels/compressible/turbulenceModel/lnInclude -I/opt/openfoam5/src/regionModels/regionModel/lnInclude -IlnInclude -I. -I/opt/openfoam5/src/OpenFOAM/lnInclude -I/opt/openfoam5/src/OSspecific/POSIX/lnInclude   -fPIC -shared -Xlinker --add-needed -Xlinker --no-as-needed Make/linux64GccDPInt32Opt/photoBioModels/photoBioModel/photoBioModel.o Make/linux64GccDPInt32Opt/photoBioModels/photoBioModel/photoBioModelNew.o Make/linux64GccDPInt32Opt/photoBioModels/photoBioDOM/photoBioDOM/photoBioDOM.o Make/linux64GccDPInt32Opt/photoBioModels/photoBioDOM/photoBioIntensityRay/photoBioIntensityRay.o Make/linux64GccDPInt32Opt/subModels/phaseFunctionModel/phaseFunctionModel/phaseFunctionModel.o Make/linux64GccDPInt32Opt/subModels/phaseFunctionModel/phaseFunctionModel/newPhaseFunctionModel.o Make/linux64GccDPInt32Opt/subModels/phaseFunctionModel/HenyeyGreensteinModel/HenyeyGreensteinModel.o Make/linux64GccDPInt32Opt/subModels/phaseFunctionModel/schlickModel/schlickModel.o Make/linux64GccDPInt32Opt/subModels/phaseFunctionModel/nullModel/nullModel.o Make/linux64GccDPInt32Opt/subModels/extinctionModel/extinctionModel/extinctionModel.o Make/linux64GccDPInt32Opt/subModels/extinctionModel/extinctionModel/newExtinctionModel.o Make/linux64GccDPInt32Opt/subModels/extinctionModel/wideBandConstantExtinction/wideBandConstantExtinction.o Make/linux64GccDPInt32Opt/subModels/extinctionModel/wideBandVariableExtinction/wideBandVariableExtinction.o Make/linux64GccDPInt32Opt/derivedFvPatchFields/diffuseEmitter/diffuseEmitterMixedFvPatchScalarField.o Make/linux64GccDPInt32Opt/derivedFvPatchFields/reflectiveSurface/reflectiveSurfaceMixedFvPatchScalarField.o Make/linux64GccDPInt32Opt/derivedFvPatchFields/surrounding/surroundingMixedFvPatchScalarField.o Make/linux64GccDPInt32Opt/derivedFvPatchFields/transExteriorSurface/transExteriorSurfaceMixedFvPatchScalarField.o Make/linux64GccDPInt32Opt/derivedFvPatchFields/transInteriorSurface/transInteriorSurfaceCoupledFvPatchScalarField.o Make/linux64GccDPInt32Opt/derivedFvPatchFields/multiBandTransInterior/multiBandTransInteriorCoupledFvPatchScalarField.o Make/linux64GccDPInt32Opt/derivedFvPatchFields/solarSurface/solarSurfaceMixedFvPatchScalarField.o Make/linux64GccDPInt32Opt/derivedFvPatchFields/wideBandSpecularRadiation/wideBandSpecularRadiationMixedFvPatchScalarField.o -L/opt/openfoam5/platforms/linux64GccDPInt32Opt/lib \
    -lfiniteVolume -lspecie -lregionModels   -o /home/openfoam/platforms/linux64GccDPInt32Opt/lib/libphotoBio.so
Making dependency list for source file multiRegionPhotoBioFoam.C
g++ -std=c++11 -m64 -Dlinux64 -DWM_ARCH_OPTION=64 -DWM_DP -DWM_LABEL_SIZE=32 -Wall -Wextra -Wold-style-cast -Wnon-virtual-dtor -Wno-unused-parameter -Wno-invalid-offsetof -O3  -DNoRepository -ftemplate-depth-100 -I.. -I/opt/openfoam5/src/finiteVolume/lnInclude -I/opt/openfoam5/src/meshTools/lnInclude -I../lnInclude -I/opt/openfoam5/src/regionModels/regionModel/lnInclude -IlnInclude -I. -I/opt/openfoam5/src/OpenFOAM/lnInclude -I/opt/openfoam5/src/OSspecific/POSIX/lnInclude   -fPIC -c multiRegionPhotoBioFoam.C -o Make/linux64GccDPInt32Opt/multiRegionPhotoBioFoam.o
g++ -std=c++11 -m64 -Dlinux64 -DWM_ARCH_OPTION=64 -DWM_DP -DWM_LABEL_SIZE=32 -Wall -Wextra -Wold-style-cast -Wnon-virtual-dtor -Wno-unused-parameter -Wno-invalid-offsetof -O3  -DNoRepository -ftemplate-depth-100 -I.. -I/opt/openfoam5/src/finiteVolume/lnInclude -I/opt/openfoam5/src/meshTools/lnInclude -I../lnInclude -I/opt/openfoam5/src/regionModels/regionModel/lnInclude -IlnInclude -I. -I/opt/openfoam5/src/OpenFOAM/lnInclude -I/opt/openfoam5/src/OSspecific/POSIX/lnInclude   -fPIC -Xlinker --add-needed -Xlinker --no-as-needed Make/linux64GccDPInt32Opt/multiRegionPhotoBioFoam.o -L/opt/openfoam5/platforms/linux64GccDPInt32Opt/lib \
    -L/home/openfoam/platforms/linux64GccDPInt32Opt/lib -lfiniteVolume -lmeshTools -lphotoBio -lOpenFOAM -ldl  \
     -lm -o /home/openfoam/platforms/linux64GccDPInt32Opt/bin/multiRegionPhotoBioFoam
Making dependency list for source file photoBioFoam.C
g++ -std=c++11 -m64 -Dlinux64 -DWM_ARCH_OPTION=64 -DWM_DP -DWM_LABEL_SIZE=32 -Wall -Wextra -Wold-style-cast -Wnon-virtual-dtor -Wno-unused-parameter -Wno-invalid-offsetof -O3  -DNoRepository -ftemplate-depth-100 -I.. -I/opt/openfoam5/src/finiteVolume/lnInclude -I/opt/openfoam5/src/meshTools/lnInclude -I../lnInclude -IlnInclude -I. -I/opt/openfoam5/src/OpenFOAM/lnInclude -I/opt/openfoam5/src/OSspecific/POSIX/lnInclude   -fPIC -c photoBioFoam.C -o Make/linux64GccDPInt32Opt/photoBioFoam.o
g++ -std=c++11 -m64 -Dlinux64 -DWM_ARCH_OPTION=64 -DWM_DP -DWM_LABEL_SIZE=32 -Wall -Wextra -Wold-style-cast -Wnon-virtual-dtor -Wno-unused-parameter -Wno-invalid-offsetof -O3  -DNoRepository -ftemplate-depth-100 -I.. -I/opt/openfoam5/src/finiteVolume/lnInclude -I/opt/openfoam5/src/meshTools/lnInclude -I../lnInclude -IlnInclude -I. -I/opt/openfoam5/src/OpenFOAM/lnInclude -I/opt/openfoam5/src/OSspecific/POSIX/lnInclude   -fPIC -Xlinker --add-needed -Xlinker --no-as-needed Make/linux64GccDPInt32Opt/photoBioFoam.o -L/opt/openfoam5/platforms/linux64GccDPInt32Opt/lib \
    -L/home/openfoam/platforms/linux64GccDPInt32Opt/lib -lfiniteVolume -lmeshTools -lphotoBio -lOpenFOAM -ldl  \
     -lm -o /home/openfoam/platforms/linux64GccDPInt32Opt/bin/photoBioFoam
